# Uncomment all lines to enable plugin default routing
#
#video:
#  url:   /video
#  param: { module: sfVideo, action: index }
#
#video_local:
#  url:   /video/:file
#  param: { module: sfVideo, action: local }
#  options:
#    segment_separators: ['/'] # disabling '.' separator
